name: docker image scanning using the trivy
on:
  workflow_dispatch:

jobs:
  docker-image-scanning:
    name: docker image scanning using the trivy
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Verify Trivy
        run: trivy --version

      - name: build docker image
        run: |
          docker build -t my-image:${{ github.sha }} ./Day-02-docker-image-scan

      - name: trivy setup
        uses: aquasecurity/trivy-action@v.28.0

      - name: scan docker image
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL my-image:${{ github.sha }}

      - name: upload trivy scan result
        uses: actions/upload-artifact@v4
        with:
          image-ref: 'my-image:${{ github.sha }}'
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
          ignore-unfixed: true

      - name: scan summary
        if: success()
        run: |
          echo "the scan completed successfully. No HIGH or CRITICAL vulnerabilities found."

      - name: upload the docker image to the github artifactory
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:{{github.sha}}